### ISSUE TITLE
doc dependencies

### ISSUE THREAD

**Issue by vap0rtranz** [Tiggilyboo/weather-mobile#1]
The Readme doc should include dependencies needed to build the app.

For postmarketOS (Alpine based), I had to install:

openssl-dev
glib-dev
cairo-dev
graphene-dev
pango-dev
gtk4.0-dev

**Comment by vap0rtranz** [comment]
P.S. the binary was built but there was an error:

```
    Finished dev [unoptimized + debuginfo] target(s) in 13m 48s
     Running `target/debug/weather-mobile`
error: could not execute process `target/debug/weather-mobile` (never executed)

Caused by:
  No such file or directory (os error 2)
```

**Comment by Tiggilyboo** [comment]
Thanks for this vap0rtranz, I've updated the README with your dependency list.

Regarding your missing file error, I think it may be due to the icons folder not getting copied to your installation path. Take a look using the RUST_BACKTRACE=1 to confirm.

Cheers

**Comment by Tiggilyboo** [comment]
> P.S. the binary was built but there was an error:
> 
> ```
>     Finished dev [unoptimized + debuginfo] target(s) in 13m 48s
>      Running `target/debug/weather-mobile`
> error: could not execute process `target/debug/weather-mobile` (never executed)
> 
> Caused by:
>   No such file or directory (os error 2)
> ```
> 

Did the above copying of icons solve your problem?
